# Use the PHP 7.3 runtime
runtime: php73

# Defaults to "serve index.php" if not specified
entrypoint: serve index.php

handlers:
  - url: /css
    static_dir: css

  - url: /images
    static_dir: images
